### PR TITLE
Do not block on sync controller start and engage existing clusters

### LINKED ISSUE #99: bug: only a single resource is actively synced
### Describe the bug

In api-syncagent 0.4.0, we introduced a regression that stops syncing objects for `PublishedResources` except for a single, randomly chosen `PublishedResource`'s object. As such, publishing more than one resource from a single api-syncagent is broken.

### Steps To Reproduce

1. Create two `PublishedResources`.
2. Create objects for both resources on the kcp side.
3. Observe only one of the objects is synced.

### Expected Behaviour

Multiple resources should be synced without problem.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by embik**
## Summary

The migration to multicluster-runtime (#72) left us with a big regression, only a single `PublishedResource`'s objects were actively synced.

Turns out, we are blocking the reconcile loop for the sync manager on the first actual sync controller we start, so no further sync controllers could be started. This PR addresses that problem.

In addition, we found a design flaw in the sync manager: Since we start controllers dynamically, an `Engage` call by a provider might not happen when a dynamic (sync) controller is already running. As such, we retrofitted dynamic engaging of existing clusters on new sync controllers to make sure we bring them up to par with any existing controllers.

## What Type of PR Is This?

/kind bug
/kind regression

## Related Issue(s)

Fixes #99 

## Release Notes

```release-note
Fix api-syncagent not reconciling objects for more than one `PublishedResource`
```

### CODE REVIEW

File: internal/controller/syncmanager/controller.go [hunk 1]
```diff
@@ -161,9 +178,9 @@ func Add(
 	return err
 }
 
-func (r *Reconciler) Reconcile(ctx context.Context, _ reconcile.Request) (reconcile.Result, error) {
+func (r *Reconciler) Reconcile(ctx context.Context, req reconcile.Request) (reconcile.Result, error) {
 	log := r.log.Named(ControllerName)
-	log.Debug("Processing")
+	log.Debugw("Processing", "request", req)
```
Comment (xrstf) [inline internal/controller/syncmanager/controller.go:183]: This controller only ever reconciles a dummy object, it has no meaning to log this dummy value.
